desc 'Subset fonts'
task default: %i[pyftsubset]

ITALIC = 'SourceSans3VF-Italic.otf.woff2'
ROMAN = 'SourceSans3VF-Roman.otf.woff2'

task :pyftsubset do
  unless File.exist? '/opt/homebrew/bin/pyftsubset'
    fail 'FAIL: pyftsubset missing! Need to install fonttools'
  end
end

%w[SourceSans3VF-Italic.otf.woff2 SourceSans3VF-Roman.otf.woff2].each do |font|
  puts font
  {
    'subset' => 'U+0000-00FF,U+20AC,U+2000-20CF',
    'latin-ext' => 'U+0100-024F',
    'greek' => 'U+0370-03FF'
  }.each do |name, range|
    output = font.sub('.woff2', ".#{name}.woff2")
    file output => font do
      sh "pyftsubset #{font} --output-file=#{output} --unicodes=\"#{
           range
         }\" --layout-features='*' --flavor=woff"
    end
    task default: output
  end
end
